### ISSUE TITLE
Memory leak during page navigation with ListViews

### ISSUE THREAD

**Issue by manodasanW** [microsoft/CsWinRT#1213]
Find attached two demo projects, the "UIOnly" folder contains the example from this [issue comment](https://github.com/microsoft/CsWinRT/issues/413#issue-702423240), ported to the latest project template. 
Additionally, the "MVVM" folder contains an example that is similar to what I try to build in my application. I had to click back and force for a long time and some memory gets freed sometimes, but the app will crash eventually. 
![image](https://user-images.githubusercontent.com/6583600/150161350-85d87db6-b69a-4b2b-a20b-89530b456b1b.png)

Hope that helps and thanks for looking into it. 

[PoC.zip](https://github.com/microsoft/CsWinRT/files/7898285/PoC.zip)

_Originally posted by @marcpiechura in https://github.com/microsoft/CsWinRT/issues/413#issuecomment-1016580898_

**Comment by TheAvonian** [comment]
Hi, I created a project using the starter WinUI3 template provided by Visual Studio.
[Here it is.](https://github.com/TheAvonian/WinUI3MemoryExample)
I also provided a gif demonstrating how every navigation adds a MB and it never stops nor gets collected.
![2022-06-29_19-28-01](https://user-images.githubusercontent.com/29378966/176564552-05874a7a-3c3c-4820-bd46-6d7f4bbcc481.gif)
This is on .NET 6.0.300, template used was navigation pane with a settings page, MSIX packaging, and MVVM structure.
This is also demonstrated via the newest WinUI 3 Gallery update from the Microsoft Store, clicking a new navigation tab adds several MB every time.

**Comment by l619534951** [comment]
> Hi, I created a project using the starter WinUI3 template provided by Visual Studio. [Here it is.](https://github.com/TheAvonian/WinUI3MemoryExample) I also provided a gif demonstrating how every navigation adds a MB and it never stops nor gets collected. ![2022-06-29_19-28-01](https://user-images.githubusercontent.com/29378966/176564552-05874a7a-3c3c-4820-bd46-6d7f4bbcc481.gif) [ ](https://user-images.githubusercontent.com/29378966/176564552-05874a7a-3c3c-4820-bd46-6d7f4bbcc481.gif) ![2022-06-29_19-28-01](https://user-images.githubusercontent.com/29378966/176564552-05874a7a-3c3c-4820-bd46-6d7f4bbcc481.gif) [ ](https://user-images.githubusercontent.com/29378966/176564552-05874a7a-3c3c-4820-bd46-6d7f4bbcc481.gif) This is on .NET 6.0.300, template used was navigation pane with a settings page, MSIX packaging, and MVVM structure. This is also demonstrated via the newest WinUI 3 Gallery update from the Microsoft Store, clicking a new navigation tab adds several MB every time.

has the same problem, operation similar to yours.(also appears when navigation stack is disabled)  
repo: https://github.com/l619534951/NavMemLeak  
I don't know whose problem it is, then I created issue in microsoft-ui-xaml https://github.com/microsoft/microsoft-ui-xaml/issues/7322

**Comment by KWodarczyk** [comment]
is there any workaround for this while we wait for the fix ? I am surprise this has not been fix yet as this affects everyone using this framework. Even WinUI 2 Galery has this issue. Come on.

**Comment by asierpn** [comment]
We have migrated our UWP app to WinUI3/WinAppSdk and all our users are reporting a significant performance improvement, there are still memory leaks in navigation, but in our stress tests they do not appear as early as they did in UWP. This team is doing a good job but these remaining issues need to be addressed soon, the navigation memory leaks have been present on this platform since its early days.

**Comment by christosk92** [comment]
For now I went ahead and implemented ContentControl navigation instead of Frame navigation. Manually disposing/getting rid of UserControl (instead of pages) seems to be doing the trick for now.

**Comment by l619534951** [comment]
> For now I went ahead and implemented ContentControl navigation instead of Frame navigation. Manually disposing/getting rid of UserControl (instead of pages) seems to be doing the trick for now.

Try Windows App SDK 1.2.0-preview2, It fixes many problems. (The memory leak of listview is fixed, but I haven't tested Frame)

**Comment by bogdan-patraucean** [comment]
@l619534951 I'm using it, it's not fixed.

**Comment by bogdan-patraucean** [comment]
It should be fixed in the [latest ](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#version-12)WindowsAppSDK version. I tested navigating back & forth and it's indeed increasing the memory but for my app it stops at around 500 MB of RAM. As far as I know there is a cache limit until which no memory will be released, so probably that's why it's still increasing.

**Comment by christosk92** [comment]
Yes it has been fixed. I believe WinAppSdk is heading in the right direction with the latest improvements in rendering. But scrolling still isn't as smooth as UWP, but I believe this will be fixed in a future release.

Well done to the team.

**Comment by Reza-Noei** [comment]
I have still this issue. 

@christosk92 my application runs with 110mb memory usage, I have several charts and after doing some navigation and loading some charts it goes to 2gb and more.

Is this `certain threshold` you mentioned above may goes higher than this or I should be hopeful to see it stop growing somewhere ?

**Comment by soroshsabz** [comment]
@christosk92 Which version resolved this problem?

**Comment by chingucoding** [comment]
@manodasanW I think this issue is not only related to ListView (maybe rename this issue?) and I also would argue it is not really fixed. Apps like Files or the WinUI Gallery still have issues with massive memory consumption.

Attached is a simple repro project: [NavigationMemoryLeak.zip](https://github.com/microsoft/CsWinRT/files/13322650/NavigationMemoryLeak.zip)

**Comment by soroshsabz** [comment]
@manodasanW any update?
