### ISSUE TITLE
Marshalling `IEnumerable<T>` in modern UWP fails

### ISSUE THREAD

**Issue by devsko** [microsoft/CsWinRT#1839]
**Describe the bug**
Calling WinRT with parameters of type `IEnumerable<T>` in modern UWP fails with various exceptions depending on `T` and parameter type.

**To Reproduce**

1. Create a new .NET 9 UWP project
2. Add `<WindowsSDKPackageVersion>10.0.26100.54</WindowsSDKPackageVersion>` and `<AllowUnsafeBlocks>true</AllowUnsafeBlocks>` to .csproj
3. Add a `Page_Loaded` handler to MainPage with this code:
```
            new Geopath([new BasicGeoposition(0, 0, 0)]); // BasicGeoposition is a value type
            // System.InvalidCastException: Specified cast is not valid.
            //    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
            //    at WinRT.ComWrappersSupport.CreateCCWForObjectForABI(Object obj, Guid iid)
            //    at WinRT.ComWrappersSupport.CreateCCWForObjectForMarshaling(Object obj, Guid iid)
            //    at WinRT.MarshalInspectable`1.CreateMarshaler2(T o, Guid iid, Boolean unwrapObject)
            //    at WinRT.MarshalInterface`1.CreateMarshaler2(T value, Guid iid)
            //    at Windows.Devices.Geolocation.Geopath._IGeopathFactoryMethods.Create(IObjectReference _obj, IEnumerable`1 positions)
            //    at Windows.Devices.Geolocation.Geopath..ctor(IEnumerable`1 positions)

            new Geopath(new BasicGeoposition[] { new(0, 0, 0) });
            // System.NotSupportedException: Cannot provide IReferenceArray`1 support for element type 'Windows.Devices.Geolocation.BasicGeoposition'.
            //    at WinRT.ComWrappersSupport.ProvideIReferenceArray(Type arrayType)
            //    at WinRT.ComWrappersSupport.GetInterfaceTableEntries(Type type)
            //    at WinRT.DefaultComWrappers.<>c.<ComputeVtables>b__7_0(Type type)
            //    at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValueLocked(TKey key, CreateValueCallback createValueCallback)
            //    at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValue(TKey key, CreateValueCallback createValueCallback)
            //    at WinRT.DefaultComWrappers.ComputeVtables(Object obj, CreateComInterfaceFlags flags, Int32& count)
            //    at System.Runtime.InteropServices.ComWrappers.TryGetOrCreateComInterfaceForObjectInternal(ObjectHandleOnStack comWrappersImpl, Int64 wrapperId, ObjectHandleOnStack instance, CreateComInterfaceFlags flags, IntPtr& retValue)
            //    at System.Runtime.InteropServices.ComWrappers.TryGetOrCreateComInterfaceForObjectInternal(ComWrappers impl, Object instance, CreateComInterfaceFlags flags, IntPtr& retValue)
            //    at System.Runtime.InteropServices.ComWrappers.GetOrCreateComInterfaceForObject(Object instance, CreateComInterfaceFlags flags)
            //    at WinRT.ComWrappersSupport.CreateCCWForObjectForABI(Object obj, Guid iid)
            //    at WinRT.ComWrappersSupport.CreateCCWForObjectForMarshaling(Object obj, Guid iid)
            //    at WinRT.MarshalInspectable`1.CreateMarshaler2(T o, Guid iid, Boolean unwrapObject)
            //    at WinRT.MarshalInterface`1.CreateMarshaler2(T value, Guid iid)
            //    at Windows.Devices.Geolocation.Geopath._IGeopathFactoryMethods.Create(IObjectReference _obj, IEnumerable`1 positions)
            //    at Windows.Devices.Geolocation.Geopath..ctor(IEnumerable`1 positions)

            MapStyleSheet.Combine([MapStyleSheet.Aerial()]); // MapStyleSheet is a reference type
            // System.InvalidCastException: Specified cast is not valid.
            //    at WinRT.ComWrappersSupport.CreateCCWForObjectForABI(Object obj, Guid iid)
            //    at WinRT.ComWrappersSupport.CreateCCWForObjectForMarshaling(Object obj, Guid iid)
            //    at WinRT.MarshalInspectable`1.CreateMarshaler2(T o, Guid iid, Boolean unwrapObject)
            //    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
            //    at WinRT.MarshalInterface`1.CreateMarshaler2(T value, Guid iid)
            //    at ABI.Windows.UI.Xaml.Controls.Maps.IMapStyleSheetStaticsMethods.Combine(IObjectReference _obj, IEnumerable`1 styleSheets)
            //    at Windows.UI.Xaml.Controls.Maps.MapStyleSheet.Combine(IEnumerable`1 styleSheets)

            MapStyleSheet.Combine(new MapStyleSheet[] { MapStyleSheet.Aerial() }); 
            // works when AllowUnsafeBlocks=true, InvalidCastException otherwise
```

**Expected behavior**

No exceptions

**Version Info**

net9.0 rc2, Windows SDK 26100

**Additional context**

Creating a `Geopath` in WinUI3 works as expected. (MapStyleSheet is not available in WinUI3)

**Comment by dongle-the-gadget** [comment]
CsWinRT does not yet support collection expressions in AOT mode. As for the reference type array, it works with unsafe code because CsWinRT needs that to generate AOT shims.

The value-type-array error does look to be an oversight though. cc @manodasanW

**Comment by manodasanW** [comment]
We didn't initially support boxing arrays using `IReferenceArray` due to we couldn't make it work with non-blittable scenarios on AOT.  But I am working on a [change](https://github.com/microsoft/CsWinRT/tree/manodasanw/IReferenceArray2) to enable it for blittable scenarios such as this one.

In the meantime, you should be able to able a list rather than an array or collection expression and it should work.

**Comment by devsko** [comment]
I tried `new Geopath(new List<BasicGeoposition>() { new(0, 0, 0) });` which gives the exact same exception as the one with collection expression.
On WinUI3 all of them work perfectly.

**Comment by manodasanW** [comment]
Can you confirm the version of the .NET 9 SDK you are using?  And to confirm, do you have `AllowUnsafeBlocks` enabled?

**Comment by devsko** [comment]
It is 9.0.100-rc.2.24474.11
I uploaded the repro https://github.com/[devsko/App10](https://github.com/devsko/App10)

**Comment by Gaoyifei1011** [comment]
![Image](https://github.com/user-attachments/assets/d8866996-eb7c-4367-891d-d5f00ed0e7d3)

https://github.com/microsoft/CsWinRT/issues/1846

Are the internal anomalous causes of the two issues consistent?

##### -------------------------------------

这俩个问题的内部异常原因是一致的吗？

**Comment by Sergio0694** [comment]
This was resolved by #1878, closing this.

**Comment by Sergio0694** [comment]
It also collects vtables for supported collection expressions (eg. when targeting concrete types or mutable interfaces).

**Comment by devsko** [comment]
Is there an ETA for version 2.3?

**Comment by devsko** [comment]
This is still not working with the 2.3 preview version (Windows SDK 10.0.26100.73-preview)
```c#
new Geopath((BasicGeoposition[])[new(0, 0, 0)]); // System.NotSupportedException: Cannot provide IReferenceArray`1 support for element type 'Windows.Devices.Geolocation.BasicGeoposition'.
new Geopath(new BasicGeoposition[] { new(0, 0, 0) }); // System.NotSupportedException: Cannot provide IReferenceArray`1 support for element type 'Windows.Devices.Geolocation.BasicGeoposition'.
new Geopath(new List<BasicGeoposition>() { new(0, 0, 0) }); // System.InvalidCastException: 'Failed to create a CCW for object of type 'System.Collections.Generic.List`1[Windows.Devices.Geolocation.BasicGeoposition]' for interface with IID '922399A8-0093-5009-A8D2-F87B0EAE75F5': the specified cast is not valid.'
```
The only way i could find to work around is to create a `IEnumerable<BasicGeoposition>` implementing wrapper class (in version 2.3 i also have to ignore the new warning).

**Comment by dongle-the-gadget** [comment]
Does adding GeneratedWinRTExposedTypeAttribute on the List help?

**Comment by devsko** [comment]
After adding `[assembly: WinRT.GeneratedWinRTExposedExternalType(typeof(List<BasicGeoposition>))]` the List variant seems to work. The array variants are still throwing NotSupportedException.

**Comment by dongle-the-gadget** [comment]
Array variants aren’t likely to work

**Comment by devsko** [comment]
I can live with that but find it confusing that the diagnostic explicitly recommends to target type the collection literal as array.
